[package]
name = "nupp-native-runtime"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
async = ["dep:tokio"]

[dependencies]
nupp-native-abi = { path = "../abi" }
tokio = { version = "1", features = ["fs", "io-util", "net", "rt-multi-thread", "sync", "time"], optional = true }
