-- Generate a host-native library from a tiny width-polymorphic SIMD IR.
--
-- The plans below are deliberately expressed once. Backend renderers choose
-- scalar, NEON, SSE2, or AVX2 spellings without changing the operation graph.

local output = assert(arg[1], "usage: generate.lua OUTPUT.c")

local function input(name)
   assert(name == "left" or name == "right")
   return {op = "input", name = name}
end

local function band(left, right)
   return {op = "and", left = left, right = right}
end

local function bnot(value)
   return {op = "not", value = value}
end

local function reduceAny(name, value, found, exhausted)
   return {
      name = name,
      value = value,
      found = found,
      exhausted = exhausted,
   }
end

local left = input("left")
local right = input("right")
local plans = {
   reduceAny("overlaps", band(left, right), 1, 0),
   reduceAny("contains_all", band(right, bnot(left)), 0, 1),
}

local backends = {
   scalar = {
      lanes = 1,
      input = function(name) return name .. "[i]" end,
      band = function(a, b) return "(" .. a .. " & " .. b .. ")" end,
      bnot = function(a) return "(~" .. a .. ")" end,
      any = function(value) return value .. " != 0" end,
   },
   neon = {
      lanes = 4,
      input = function(name) return "vld1q_u32(" .. name .. " + i)" end,
      band = function(a, b) return "vandq_u32(" .. a .. ", " .. b .. ")" end,
      bnot = function(a) return "vmvnq_u32(" .. a .. ")" end,
      any = function(value) return "vmaxvq_u32(" .. value .. ") != 0" end,
   },
   sse2 = {
      lanes = 4,
      input = function(name)
         return "_mm_loadu_si128((const __m128i *)(const void *)(" .. name .. " + i))"
      end,
      band = function(a, b) return "_mm_and_si128(" .. a .. ", " .. b .. ")" end,
      bnot = function(a) return "_mm_xor_si128(" .. a .. ", _mm_set1_epi32(-1))" end,
      any = function(value)
         return "_mm_movemask_epi8(_mm_cmpeq_epi8(" .. value .. ", _mm_setzero_si128())) != 0xffff"
      end,
   },
   avx2 = {
      lanes = 8,
      input = function(name)
         return "_mm256_loadu_si256((const __m256i *)(const void *)(" .. name .. " + i))"
      end,
      band = function(a, b) return "_mm256_and_si256(" .. a .. ", " .. b .. ")" end,
      bnot = function(a) return "_mm256_xor_si256(" .. a .. ", _mm256_set1_epi32(-1))" end,
      any = function(value) return "_mm256_testz_si256(" .. value .. ", " .. value .. ") == 0" end,
   },
}

local function expression(node, backend)
   local renderer = assert(backends[backend], backend)
   if node.op == "input" then
      return renderer.input(node.name)
   elseif node.op == "and" then
      return renderer.band(expression(node.left, backend), expression(node.right, backend))
   elseif node.op == "not" then
      return renderer.bnot(expression(node.value, backend))
   end
   error("unknown SIMD IR operation " .. tostring(node.op))
end

local lines = {}
local function emit(line)
   lines[#lines + 1] = line or ""
end

emit("/* Generated by bench/simd-polymorphism-spike/generate.lua. */")
emit("#include <stddef.h>")
emit("#include <stdint.h>")
emit("#include <stdatomic.h>")
emit("")
emit("#if defined(__aarch64__) || defined(__arm64__)")
emit("#include <arm_neon.h>")
emit("#elif defined(__x86_64__) || defined(_M_X64)")
emit("#include <immintrin.h>")
emit("#endif")
emit("")

local function emitScalar(plan)
   local test = backends.scalar.any(expression(plan.value, "scalar"))
   emit("__attribute__((noinline))")
   emit("int ss_" .. plan.name .. "_scalar(const uint32_t *left, const uint32_t *right, size_t count) {")
   emit("#if defined(__clang__)")
   emit("#pragma clang loop vectorize(disable) interleave(disable)")
   emit("#endif")
   emit("    for (size_t i = 0; i < count; ++i) {")
   emit("        if (" .. test .. ") return " .. plan.found .. ";")
   emit("    }")
   emit("    return " .. plan.exhausted .. ";")
   emit("}")
   emit("")
end

local function emitVector(plan, backend, attribute)
   local renderer = backends[backend]
   local vectorTest = renderer.any(expression(plan.value, backend))
   local scalarTest = backends.scalar.any(expression(plan.value, "scalar"))
   if attribute then emit(attribute) end
   emit("static int ss_" .. plan.name .. "_" .. backend ..
      "(const uint32_t *left, const uint32_t *right, size_t count) {")
   emit("    size_t i = 0;")
   emit("    for (; i + " .. renderer.lanes .. " <= count; i += " .. renderer.lanes .. ") {")
   emit("        if (" .. vectorTest .. ") return " .. plan.found .. ";")
   emit("    }")
   emit("    for (; i < count; ++i) {")
   emit("        if (" .. scalarTest .. ") return " .. plan.found .. ";")
   emit("    }")
   emit("    return " .. plan.exhausted .. ";")
   emit("}")
   emit("")
end

for _, plan in ipairs(plans) do emitScalar(plan) end

emit("#if defined(__aarch64__) || defined(__arm64__)")
for _, plan in ipairs(plans) do emitVector(plan, "neon") end
emit("#elif defined(__x86_64__) || defined(_M_X64)")
for _, plan in ipairs(plans) do
   emitVector(plan, "sse2", "__attribute__((target(\"sse2\")))")
   emitVector(plan, "avx2", "__attribute__((target(\"avx2\")))")
end
emit("#endif")
emit("")

emit("enum { SS_UNKNOWN = 0, SS_SCALAR = 1, SS_NEON = 2, SS_SSE2 = 3, SS_AVX2 = 4 };")
emit("static atomic_int ss_selected = ATOMIC_VAR_INIT(SS_UNKNOWN);")
emit("")
emit("static int ss_select_backend(void) {")
emit("    int selected = atomic_load_explicit(&ss_selected, memory_order_acquire);")
emit("    if (selected != SS_UNKNOWN) return selected;")
emit("#if defined(__aarch64__) || defined(__arm64__)")
emit("    int detected = SS_NEON;")
emit("#elif defined(__x86_64__) || defined(_M_X64)")
emit("    __builtin_cpu_init();")
emit("    int detected = __builtin_cpu_supports(\"avx2\") ? SS_AVX2 : SS_SSE2;")
emit("#else")
emit("    int detected = SS_SCALAR;")
emit("#endif")
emit("    int expected = SS_UNKNOWN;")
emit("    atomic_compare_exchange_strong_explicit(&ss_selected, &expected, detected,")
emit("        memory_order_release, memory_order_relaxed);")
emit("    return atomic_load_explicit(&ss_selected, memory_order_acquire);")
emit("}")
emit("")

emit("const char *ss_backend(void) {")
emit("    switch (ss_select_backend()) {")
emit("        case SS_NEON: return \"neon\";")
emit("        case SS_SSE2: return \"sse2\";")
emit("        case SS_AVX2: return \"avx2\";")
emit("        default: return \"scalar\";")
emit("    }")
emit("}")
emit("")
emit("uint32_t ss_lanes_u32(void) {")
emit("    switch (ss_select_backend()) {")
emit("        case SS_NEON: return 4;")
emit("        case SS_SSE2: return 4;")
emit("        case SS_AVX2: return 8;")
emit("        default: return 1;")
emit("    }")
emit("}")
emit("")

for _, plan in ipairs(plans) do
   emit("int ss_" .. plan.name .. "(const uint32_t *left, const uint32_t *right, size_t count) {")
   emit("    switch (ss_select_backend()) {")
   emit("#if defined(__aarch64__) || defined(__arm64__)")
   emit("        case SS_NEON: return ss_" .. plan.name .. "_neon(left, right, count);")
   emit("#elif defined(__x86_64__) || defined(_M_X64)")
   emit("        case SS_AVX2: return ss_" .. plan.name .. "_avx2(left, right, count);")
   emit("        case SS_SSE2: return ss_" .. plan.name .. "_sse2(left, right, count);")
   emit("#endif")
   emit("        default: return ss_" .. plan.name .. "_scalar(left, right, count);")
   emit("    }")
   emit("}")
   emit("")
end

local file = assert(io.open(output, "wb"))
assert(file:write(table.concat(lines, "\n"), "\n"))
assert(file:close())
