[package]
name = "nupp-native-checksum"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
name = "nupp_crc"
crate-type = ["rlib", "cdylib"]

[features]
default = []
ffi = []

[dependencies]
crc-fast = { version = "1.10.0", default-features = false, features = ["std"] }
nupp-native-abi = { path = "../abi" }
