[package]
name = "nupp-native-gpu"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
nupp-native-abi = { path = "../abi" }
pollster = "0.4"
wgpu = { version = "30.0.1", default-features = false, features = ["parking_lot", "spirv", "std"] }

[target.'cfg(target_os = "macos")'.dependencies]
wgpu = { version = "30.0.1", default-features = false, features = ["metal"] }

[target.'cfg(target_os = "windows")'.dependencies]
wgpu = { version = "30.0.1", default-features = false, features = ["dx12", "vulkan"] }

[target.'cfg(all(unix, not(target_os = "macos")))'.dependencies]
wgpu = { version = "30.0.1", default-features = false, features = ["gles", "vulkan"] }

[dev-dependencies]
wgpu = { version = "30.0.1", default-features = false, features = ["wgsl"] }
