#!/usr/bin/env node
// Packages the host channel app against a built browser guest and runs programs
// in it under headless Chromium.
//
//   node bench/host-channel/run.mjs contract           every contract scenario
//   node bench/host-channel/run.mjs bench OUTPUT.json  the workloads, raw samples
//
// NUPP_BROWSER_GUEST_DIR names the guest (a Linux build, or the CI
// `luajit-browser-guest` artifact). Programs run one at a time in fresh pages:
// a guest is one VM, and two in parallel measure each other.

import {createServer} from "node:http";
import {copyFileSync, createReadStream, mkdirSync, readFileSync, writeFileSync} from "node:fs";
import {stat} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {packageBrowserApp} from "../../runtime/luajit/package-browser-app.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../..");
const site = path.join(repo, "build/host-channel/site");
const {chromium} = await import(path.join(repo, "editors/playground/node_modules/playwright/index.mjs"));

// The app carries the programs as text, so a change to them repackages it.
function writeSources() {
  const files = {
    "scenarios.lua": readFileSync(path.join(repo, "tests/hostchannel/scenarios.lua"), "utf8"),
    "bench.lua": readFileSync(path.join(here, "bench.lua"), "utf8"),
  };
  const level = "=".repeat(8);
  const entries = Object.entries(files).map(([name, text]) => {
    if (text.includes(`]${level}]`)) throw new Error(`${name} contains its own long-string terminator`);
    return `    [${JSON.stringify(name)}] = [${level}[\n${text}]${level}],`;
  });
  writeFileSync(path.join(here, "app/src/sources.nupp"),
    `-- Generated by bench/host-channel/run.mjs; do not edit.\nreturn {\n${entries.join("\n")}\n}\n`);
  copyFileSync(path.join(repo, "tests/hostchannel/component/src/hostevents.nupp"), path.join(here, "app/src/hostevents.nupp"));
}

async function prepare() {
  writeSources();
  mkdirSync(site, {recursive: true});
  await packageBrowserApp({project: path.join(here, "app"), target: "app", output: path.join(site, "app")});
  for (const name of ["page.html", "page.mjs", "handlers.mjs", "relay.html", "relay.mjs", "relay-worker.mjs"]) {
    copyFileSync(path.join(here, name), path.join(site, name));
  }
}

function serve() {
  const server = createServer(async (request, response) => {
    try {
      const url = new URL(request.url, "http://localhost");
      const file = path.resolve(site, "." + decodeURIComponent(url.pathname));
      if (!file.startsWith(site + path.sep) || !(await stat(file)).isFile()) throw new Error("not found");
      response.setHeader("Content-Type", file.endsWith(".mjs") ? "text/javascript"
        : file.endsWith(".html") ? "text/html" : file.endsWith(".json") ? "application/json" : "application/octet-stream");
      response.setHeader("Cache-Control", "no-store");
      createReadStream(file).pipe(response);
    } catch {
      response.writeHead(404);
      response.end("not found");
    }
  });
  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(0, "127.0.0.1", () => resolve(server));
  });
}

async function runRelay(browser, base, name) {
  const page = await browser.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(String(error)));
  try {
    await page.goto(new URL(`relay.html?name=${encodeURIComponent(name)}`, base).href);
    await page.waitForFunction(() => ["passed", "failed"].includes(document.querySelector("#result")?.dataset.status),
      null, {timeout: 600000});
    return {...JSON.parse(await page.locator("#result").textContent()), errors};
  } finally {
    await page.close();
  }
}

async function runProgram(browser, base, file, name, options = {}, audio = 0) {
  const page = await browser.newPage();
  const errors = [];
  page.on("pageerror", (error) => errors.push(String(error)));
  try {
    const url = new URL(`page.html?file=${encodeURIComponent(file)}&name=${encodeURIComponent(name)}` +
      `&options=${encodeURIComponent(JSON.stringify(options))}&audio=${audio}`, base);
    await page.goto(url.href);
    await page.waitForFunction(() => ["passed", "failed"].includes(document.querySelector("#result")?.dataset.status),
      null, {timeout: 600000});
    const result = JSON.parse(await page.locator("#result").textContent());
    return {...result, errors};
  } finally {
    await page.close();
  }
}

const CONTRACT = {
  arity: (value) => value.echoed.n === 5 && value.echoed.a === 1 && value.echoed.c === "two" &&
    value.echoed.d === true && value.none === 0 && value.onlyNil === 1 && value.interior.n === 3 &&
    value.interior.b === 2,
  refusals: (value) => /argument 1 is not a finite number/.test(value.nan) &&
    /no host answers test\.nobody/.test(value.unknown) && /failed because why/.test(value.failed),
  bytes: (value) => value.small && value.large && value.three && value.made && value.empty,
  slowCallBesideADeadline: (value) => value.slow === 4096 && value.firedAfter >= 50 && value.firedAfter < 1000,
  lateReleases: (value) => /deadline/.test(value.cancelled) && value.live === 0,
  lateCannotWait: (value) => value.echoed === "still answering" && value.live === 1,
  cancelBeforeShipping: (value) => value.cancelled === true && value.seen === 0,
  cancelMidFetch: (value) => value.cancelled === true && value.live === 0 && value.after === 8 * 1024 * 1024,
  concurrentLargeResults: (value) => value.sizes.every((size) => size === 8 * 1024 * 1024) &&
    /more than the 8 MiB/.test(value.tooLarge) && value.live === 0,
  manySmallCalls: (value) => value.correct === 600,
  posts: (value) => value.notes === "1:100,2:100,3:100,4:100,5:100,6:100,7:100,8:100,9:100,10:100",
  streams: (value) => value.moves === "3,30 4,40 5,50" && value.keys === "b-" && value.order === "b- 3,30 4,40 5,50" && value.dropped === 2 &&
    value.outbound === "packet:4 log:two log:three block:x block:y block:z",
};

const mode = process.argv[2] || "contract";
await prepare();
const server = await serve();
const base = `http://127.0.0.1:${server.address().port}/`;
// CI runs the runner's Chrome, as the browser matrix does; locally, Playwright's.
const browser = await chromium.launch({
  headless: true,
  ...(process.env.CI ? {channel: "chrome"} : {}),
  args: ["--autoplay-policy=no-user-gesture-required", ...(process.env.CI ? ["--no-sandbox"] : [])],
});
let failed = false;
try {
  if (mode === "contract") {
    for (const [name, accepts] of Object.entries(CONTRACT)) {
      const result = await runProgram(browser, base, "scenarios.lua", name);
      const value = result.outcome?.value;
      const passed = result.ok && value !== undefined && accepts(value);
      failed ||= !passed;
      console.log(`${passed ? "ok" : "FAIL"} ${name} ${Math.round(result.elapsedMs || 0)} ms` +
        (passed ? "" : ` ${JSON.stringify(result)}`));
    }
  } else if (mode === "bench") {
    const output = process.argv[3] || path.join(repo, "build/host-channel/browser-bench.json");
    const {workloads} = await import("./workloads.mjs");
    const results = [];
    for (const workload of workloads) {
      const result = await runProgram(browser, base, "bench.lua", workload.program, workload.options);
      if (!result.ok) failed = true;
      results.push({workload: workload.name, ...result});
      console.log(`${result.ok ? "ok" : "FAIL"} ${workload.name}`, JSON.stringify(result.outcome?.value?.summary ?? result));
    }
    writeFileSync(output, JSON.stringify({browser: browser.version(), recorded: new Date().toISOString(), results}, null, 2) + "\n");
    console.log(`raw samples in ${output}`);
  } else if (mode === "relay") {
    // Through the packaged entry: handlers on the page and in a Worker module.
    for (const name of ["arity", "refusals", "bytes", "lateReleases", "cancelMidFetch", "streams", "posts"]) {
      const result = await runRelay(browser, base, name);
      const value = result.outcome?.value;
      const passed = result.ok && result.outcome?.ok && value !== undefined && CONTRACT[name](value);
      failed ||= !passed;
      console.log(`${passed ? "ok" : "FAIL"} relay ${name}` + (passed ? "" : ` ${JSON.stringify(result).slice(0, 800)}`));
    }
  } else if (mode === "audio") {
    // W6: each buffer-ahead, without stalls and with a 50 ms and a 150 ms one.
    const output = process.argv[3] || path.join(repo, "build/host-channel/audio-bench.json");
    const seconds = Number(process.argv[4] || 20);
    const results = [];
    for (const bufferAheadMs of [10, 20, 30, 50, 80]) {
      for (const stalls of [[], [{at: seconds * 300, ms: 50}, {at: seconds * 600, ms: 150}]]) {
        const result = await runProgram(browser, base, "bench.lua", "audio", {seconds, stalls}, bufferAheadMs);
        if (!result.ok) failed = true;
        const summary = result.outcome?.value?.summary;
        results.push({bufferAheadMs, stalls: stalls.length, ...result});
        console.log(`${result.ok ? "ok" : "FAIL"} buffer ${bufferAheadMs} ms, ${stalls.length ? "stalls" : "steady"}:`,
          JSON.stringify(summary ?? result));
      }
    }
    writeFileSync(output, JSON.stringify({browser: browser.version(), recorded: new Date().toISOString(), results}, null, 2) + "\n");
    console.log(`raw samples in ${output}`);
  } else {
    throw new Error(`unknown mode ${mode}`);
  }
} finally {
  await browser.close();
  server.close();
}
process.exit(failed ? 1 : 0);
